spring:
  cloud:
    gateway:
      routes:
        - id: service-mesh1
          uri: http://service-mesh1:8080/
          predicates:
            - Path=/service-mesh1/**
        - id: service-mesh2
          uri: http://service-mesh2:8081/
          predicates:
            - Path=/service-mesh2/**
  mvc:
    throw-exception-if-no-handler-found: true
#server:
#  port: 8080
logging:
  level:
    org.springframework: debug
